### ISSUE TITLE
# Frontend Routes

### ISSUE THREAD

**Issue by andy-h-2016** [annieyang1993/DoorDash#6]
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by andy-h-2016** [comment]
Please format the frontend routes inside the ```. It is too difficult to tell what is going on.

**Comment by annieyang1993** [comment]
Got it thanks! I think it's formatted correctly with ``` now

**Comment by andy-h-2016** [comment]
**Formatting**
Sorry I told you the wrong thing last time with the ```. What I meant to say was to format it with the indented bullet list because it was all jumbled up before. In order to get the * to show as bullets, the ``` needs to be removed from the top and the bottom. To indent with *, put 2 spaces in front for each level of indentation you want to go. I did the first 2 bullet points for you as an example.

**Content**
